#   Description:
#   CDS_WO_03.py
#   Creation of RFQ and RFQ lines for a Quote Request Line
#
#   Subversion Info
#   ---------------
#   $Id$
#
#
#   Revision History
#   ----------------
#   Created:    27/10/2015
#   --------------------------------------------------------------------------
#   Version Description                             CMS Ref         Changed By
#   -------+---------------------------------------+---------------+----------
#   1.0      Initial version                            N/A          A Rotaru
#   1.1      Add required date to RFQ                                A Rotaru
#   1.2      Create vendor lines (default vendor)                    A Rotaru
#    
#   Launch Point Variables
#   ----------------------
#                                         Action launch point
#
#   Relationships
#   -------------
#   WORKORDER.RFQ
#   RFQ.RFQLINE

from psdi.mbo import Mbo
from psdi.mbo import MboRemote 
from psdi.mbo import MboSet
from psdi.mbo import MboValue
from psdi.mbo import MboConstants
from psdi.app.workorder import WO
from psdi.server import MXServer
from java.util import Date

rfqMboSet = mbo.getMboSet("RFQ")
rfqCount = rfqMboSet.count()

if rfqCount == 0:
  rfqMbo = rfqMboSet.add()
  rfqMbo.setValue("DESCRIPTION","RFQ Autogenerated for Quote Request Line " + mbo.getString("WONUM"))
  rfqMbo.setValue("SHIPTO","BIRMINGHAM")
  rfqMbo.setValue("RFQ1",mbo.getString("WONUM"))
  rfqMbo.setValue("REQUIREDDATE",Date())
  
  #Find if the item has default (preferred) vendors
  itemPrefVendSet = mbo.getMboSet("CDS_ITEMNUM.INVVENDORDEF")
  itemPrefVendCount = itemPrefVendSet.count()
  if itemPrefVendCount != 0:
    itemPrefVendMbo = itemPrefVendSet.getMbo(0)
    rfqVendorSet = mbo.getMboSet("RFQ.RFQVENDOR")
    rfqVendorMbo = rfqVendorSet.add()
    rfqVendorMbo.setValue("VENDOR",itemPrefVendMbo.getString("VENDOR"))
    rfqVendorMbo.setValue("CUSTOMERNUM","Default Vendor")
  
  rfqLineMboSet = rfqMbo.getMboSet("RFQLINE")
  rfqLineMbo = rfqLineMboSet.add()
  rfqLineMbo.setValue("ITEMNUM",mbo.getString("CDS_ITEMNUM"))
  rfqLineMbo.setValue("ORDERQTY",mbo.getInt("REQ_QTY_1"))
  rfqLineMbo.setValue("WONUM",mbo.getString("WONUM"))
  rfqLineMbo.setValue("LINETYPE","ITEM")
  rfqLineMbo.setValue("ITEMSETID","ITEMSET")
  rfqLineMbo.setValue("REQ_QTY_NUM",1)
  rfqLineMbo.setValue("LINENUM",10)
  
  if mbo.getInt("REQ_QTY_2") is not None and mbo.getInt("REQ_QTY_2")!=0:
    rfqLineMbo = rfqLineMboSet.add()
    rfqLineMbo.setValue("ITEMNUM",mbo.getString("CDS_ITEMNUM"))
    rfqLineMbo.setValue("ORDERQTY",mbo.getInt("REQ_QTY_2"))
    rfqLineMbo.setValue("WONUM",mbo.getString("WONUM"))
    rfqLineMbo.setValue("LINETYPE","ITEM")
    rfqLineMbo.setValue("ITEMSETID","ITEMSET")
    rfqLineMbo.setValue("REQ_QTY_NUM",2)
    rfqLineMbo.setValue("LINENUM",20)
	
  if mbo.getInt("REQ_QTY_3") is not None and mbo.getInt("REQ_QTY_3")!=0:
    rfqLineMbo = rfqLineMboSet.add()
    rfqLineMbo.setValue("ITEMNUM",mbo.getString("CDS_ITEMNUM"))
    rfqLineMbo.setValue("ORDERQTY",mbo.getInt("REQ_QTY_3"))
    rfqLineMbo.setValue("WONUM",mbo.getString("WONUM"))
    rfqLineMbo.setValue("LINETYPE","ITEM")
    rfqLineMbo.setValue("ITEMSETID","ITEMSET")
    rfqLineMbo.setValue("REQ_QTY_NUM",3)
    rfqLineMbo.setValue("LINENUM",30)

  if mbo.getInt("REQ_QTY_4") is not None and mbo.getInt("REQ_QTY_4")!=0:
    rfqLineMbo = rfqLineMboSet.add()
    rfqLineMbo.setValue("ITEMNUM",mbo.getString("CDS_ITEMNUM"))
    rfqLineMbo.setValue("ORDERQTY",mbo.getInt("REQ_QTY_4"))
    rfqLineMbo.setValue("WONUM",mbo.getString("WONUM"))
    rfqLineMbo.setValue("LINETYPE","ITEM")
    rfqLineMbo.setValue("ITEMSETID","ITEMSET")
    rfqLineMbo.setValue("REQ_QTY_NUM",4)
    rfqLineMbo.setValue("LINENUM",40)

  rfqMboSet.save()